# Generated by Django 2.2.7 on 2020-04-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='active_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choices',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choices',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
    ]
