# Generated by Django 2.2.7 on 2020-04-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200415_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='active_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='new_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='total_cases',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
