# Generated by Django 2.2.7 on 2020-04-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200415_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
    ]
